[general]
import = ["~/.config/alacritty/colors/rose-pine.toml", "~/.config/alacritty/extended-keys.toml"]

[window]
dynamic_padding = true
decorations = "Full"
opacity = 1.0
blur = false

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "Ubuntu Mono", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 14  # Ubuntu Mono: 14 | FiraCode: 12 | Monocraft: 13.5

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Never" }
unfocused_hollow = true
thickness = 0.2
