# Alacritty
# https://github.com/alacritty/alacritty
# https://github.com/alacritty/alacritty/blob/master/alacritty.yml
#
# Documents:
#
# Fix keyboard input on terminals: http://www.leonerd.org.uk/hacks/fixterms/
# Key names: https://docs.rs/glutin/latest/glutin/event/enum.VirtualKeyCode.html
#
# Useful commands to get code-points and key names:
#
# showkey --ascii
# alacritty --print-events

[keyboard]
bindings = [
    {key = "C", mods = "Control|Shift", action = "Copy"},
    {key = "C", mods = "Control|Shift", chars = "\u001b[67;6u"},
    {key = "V", mods = "Control|Shift", action = "Paste"},
    {key = "H", mods = "Control", chars = "\u001b[104;5u"},
    {key = "I", mods = "Control", chars = "\u001b[105;5u"},
    {key = "J", mods = "Control", chars = "\u001b[106;5u"},
    {key = "M", mods = "Control", chars = "\u001b[109;5u"},
    {key = "A", mods = "Control|Shift", chars = "\u001b[65;6u"},
    {key = "D", mods = "Control|Shift", chars = "\u001b[68;6u"},
    {key = "E", mods = "Control|Shift", chars = "\u001b[69;6u"},
    {key = "G", mods = "Control|Shift", chars = "\u001b[71;6u"},
    {key = "H", mods = "Control|Shift", chars = "\u001b[72;6u"},
    {key = "I", mods = "Control|Shift", chars = "\u001b[73;6u"},
    {key = "J", mods = "Control|Shift", chars = "\u001b[74;6u"},
    {key = "K", mods = "Control|Shift", chars = "\u001b[75;6u"},
    {key = "L", mods = "Control|Shift", chars = "\u001b[76;6u"},
    {key = "M", mods = "Control|Shift", chars = "\u001b[77;6u"},
    {key = "O", mods = "Control|Shift", chars = "\u001b[79;6u"},
    {key = "P", mods = "Control|Shift", chars = "\u001b[80;6u"},
    {key = "Q", mods = "Control|Shift", chars = "\u001b[81;6u"},
    {key = "R", mods = "Control|Shift", chars = "\u001b[82;6u"},
    {key = "S", mods = "Control|Shift", chars = "\u001b[83;6u"},
    {key = "T", mods = "Control|Shift", chars = "\u001b[84;6u"},
    {key = "W", mods = "Control|Shift", chars = "\u001b[87;6u"},
    {key = "X", mods = "Control|Shift", chars = "\u001b[88;6u"},
    {key = "Y", mods = "Control|Shift", chars = "\u001b[89;6u"},
    {key = "Z", mods = "Control|Shift", chars = "\u001b[90;6u"},
    {key = "Key1", mods = "Control", chars = "\u001b[49;5u"},
    {key = "Key2", mods = "Control", chars = "\u001b[50;5u"},
    {key = "Key3", mods = "Control", chars = "\u001b[51;5u"},
    {key = "Key4", mods = "Control", chars = "\u001b[52;5u"},
    {key = "Key5", mods = "Control", chars = "\u001b[53;5u"},
    {key = "Key6", mods = "Control", chars = "\u001b[54;5u"},
    {key = "Key7", mods = "Control", chars = "\u001b[55;5u"},
    {key = "Key8", mods = "Control", chars = "\u001b[56;5u"},
    {key = "Key9", mods = "Control", chars = "\u001b[57;5u"},
    {key = "Key0", mods = "Control|Shift", chars = "\u001b[48;6u"},
    {key = "Key1", mods = "Control|Shift", chars = "\u001b[49;6u"},
    {key = "Key2", mods = "Control|Shift", chars = "\u001b[50;6u"},
    {key = "Key3", mods = "Control|Shift", chars = "\u001b[51;6u"},
    {key = "Key4", mods = "Control|Shift", chars = "\u001b[52;6u"},
    {key = "Key5", mods = "Control|Shift", chars = "\u001b[53;6u"},
    {key = "Key6", mods = "Control|Shift", chars = "\u001b[54;6u"},
    {key = "Key7", mods = "Control|Shift", chars = "\u001b[55;6u"},
    {key = "Key8", mods = "Control|Shift", chars = "\u001b[56;6u"},
    {key = "Key9", mods = "Control|Shift", chars = "\u001b[57;6u"},
    {key = "A", mods = "Alt", chars = "\u001ba"},
    {key = "B", mods = "Alt", chars = "\u001bb"},
    {key = "C", mods = "Alt", chars = "\u001bc"},
    {key = "D", mods = "Alt", chars = "\u001bd"},
    {key = "E", mods = "Alt", chars = "\u001be"},
    {key = "F", mods = "Alt", chars = "\u001bf"},
    {key = "G", mods = "Alt", chars = "\u001bg"},
    {key = "H", mods = "Alt", chars = "\u001bh"},
    {key = "I", mods = "Alt", chars = "\u001bi"},
    {key = "J", mods = "Alt", chars = "\u001bj"},
    {key = "K", mods = "Alt", chars = "\u001bk"},
    {key = "L", mods = "Alt", chars = "\u001bl"},
    {key = "M", mods = "Alt", chars = "\u001bm"},
    {key = "N", mods = "Alt", chars = "\u001bn"},
    {key = "O", mods = "Alt", chars = "\u001bo"},
    {key = "P", mods = "Alt", chars = "\u001bp"},
    {key = "Q", mods = "Alt", chars = "\u001bq"},
    {key = "R", mods = "Alt", chars = "\u001br"},
    {key = "S", mods = "Alt", chars = "\u001bs"},
    {key = "T", mods = "Alt", chars = "\u001bt"},
    {key = "U", mods = "Alt", chars = "\u001bu"},
    {key = "V", mods = "Alt", chars = "\u001bv"},
    {key = "W", mods = "Alt", chars = "\u001bw"},
    {key = "X", mods = "Alt", chars = "\u001bx"},
    {key = "Y", mods = "Alt", chars = "\u001by"},
    {key = "Z", mods = "Alt", chars = "\u001bz"},
    {key = "A", mods = "Alt|Shift", chars = "\u001bA"},
    {key = "B", mods = "Alt|Shift", chars = "\u001bB"},
    {key = "C", mods = "Alt|Shift", chars = "\u001bC"},
    {key = "D", mods = "Alt|Shift", chars = "\u001bD"},
    {key = "E", mods = "Alt|Shift", chars = "\u001bE"},
    {key = "F", mods = "Alt|Shift", chars = "\u001bF"},
    {key = "G", mods = "Alt|Shift", chars = "\u001bG"},
    {key = "H", mods = "Alt|Shift", chars = "\u001bH"},
    {key = "I", mods = "Alt|Shift", chars = "\u001bI"},
    {key = "J", mods = "Alt|Shift", chars = "\u001bJ"},
    {key = "K", mods = "Alt|Shift", chars = "\u001bK"},
    {key = "L", mods = "Alt|Shift", chars = "\u001bL"},
    {key = "M", mods = "Alt|Shift", chars = "\u001bM"},
    {key = "N", mods = "Alt|Shift", chars = "\u001bN"},
    {key = "O", mods = "Alt|Shift", chars = "\u001bO"},
    {key = "P", mods = "Alt|Shift", chars = "\u001bP"},
    {key = "Q", mods = "Alt|Shift", chars = "\u001bQ"},
    {key = "R", mods = "Alt|Shift", chars = "\u001bR"},
    {key = "S", mods = "Alt|Shift", chars = "\u001bS"},
    {key = "T", mods = "Alt|Shift", chars = "\u001bT"},
    {key = "U", mods = "Alt|Shift", chars = "\u001bU"},
    {key = "V", mods = "Alt|Shift", chars = "\u001bV"},
    {key = "W", mods = "Alt|Shift", chars = "\u001bW"},
    {key = "X", mods = "Alt|Shift", chars = "\u001bX"},
    {key = "Y", mods = "Alt|Shift", chars = "\u001bY"},
    {key = "Z", mods = "Alt|Shift", chars = "\u001bZ"},
    {key = "Key0", mods = "Alt", chars = "\u001b0"},
    {key = "Key1", mods = "Alt", chars = "\u001b1"},
    {key = "Key2", mods = "Alt", chars = "\u001b2"},
    {key = "Key3", mods = "Alt", chars = "\u001b3"},
    {key = "Key4", mods = "Alt", chars = "\u001b4"},
    {key = "Key5", mods = "Alt", chars = "\u001b5"},
    {key = "Key6", mods = "Alt", chars = "\u001b6"},
    {key = "Key7", mods = "Alt", chars = "\u001b7"},
    {key = "Key8", mods = "Alt", chars = "\u001b8"},
    {key = "Key9", mods = "Alt", chars = "\u001b9"},
    {key = "Minus", mods = "Alt", chars = "\u001b-"},
    {key = "Equals", mods = "Alt", chars = "\u001b="},
    {key = "LBracket", mods = "Alt", chars = "\u001b["},
    {key = "RBracket", mods = "Alt", chars = "\u001b]"},
    {key = "Backslash", mods = "Alt", chars = "\u001b\\"},
    {key = "Semicolon", mods = "Alt", chars = "\u001b;"},
    {key = "Comma", mods = "Alt", chars = "\u001b,"},
    {key = "Period", mods = "Alt", chars = "\u001b."},
    {key = "Slash", mods = "Alt", chars = "\u001b/"},
    {key = "Key1", mods = "Alt|Shift", chars = "\u001b!"},
    {key = "Key2", mods = "Alt|Shift", chars = "\u001b@"},
    {key = "Key3", mods = "Alt|Shift", chars = "\u001b#"},
    {key = "Key4", mods = "Alt|Shift", chars = "\u001b$"},
    {key = "Key5", mods = "Alt|Shift", chars = "\u001b%"},
    {key = "Key6", mods = "Alt|Shift", chars = "\u001b^"},
    {key = "Key7", mods = "Alt|Shift", chars = "\u001b&"},
    {key = "Key8", mods = "Alt|Shift", chars = "\u001b*"},
    {key = "Key9", mods = "Alt|Shift", chars = "\u001b("},
    {key = "Key0", mods = "Alt|Shift", chars = "\u001b)"},
    {key = "Minus", mods = "Alt|Shift", chars = "\u001b_"},
    {key = "Equals", mods = "Alt|Shift", chars = "\u001b+"},
    {key = "LBracket", mods = "Alt|Shift", chars = "\u001b{"},
    {key = "RBracket", mods = "Alt|Shift", chars = "\u001b}"},
    {key = "Backslash", mods = "Alt|Shift", chars = "\u001b|"},
    {key = "Semicolon", mods = "Alt|Shift", chars = "\u001b:"},
    {key = "Comma", mods = "Alt|Shift", chars = "\u001b<"},
    {key = "Period", mods = "Alt|Shift", chars = "\u001b>"},
    {key = "Slash", mods = "Alt|Shift", chars = "\u001b?"},
    {key = "Return", mods = "Control", chars = "\u001b[13;5u"},
    {key = "Return", mods = "Shift", chars = "\u001b[13;2u"},
    {key = "Space", mods = "Shift", chars = "\u001b[32;2u"},
    {key = "Tab", mods = "Control", chars = "\u001b[9;5u"},
    {key = "Tab", mods = "Shift", chars = "\u001b[9;2u"},
    {key = "Tab", mods = "Control|Shift", chars = "\u001b[9;6u"},
    {key = "Comma", mods = "Control", chars = "\u001b[44;5u"},
    {key = "Period", mods = "Control", chars = "\u001b[46;5u"},
    {key = "Semicolon", mods = "Control", chars = "\u001b[59;5u"},
    {key = "Back", mods = "Control", chars = "\u0017"},
    {key = "Slash", mods = "Control", chars = "\u001b[47;5u"},
    {key = "Backslash", mods = "Control", chars = "\u001b[92;5u"},
    {key = "Escape", mods = "Control", chars = "\u001b[27;5u"},
]
